"""
Azure Architecture Diagram: Multi-Tier E-Commerce Platform
Generated by diagram-generator agent
Date: 2025-12-01

Prerequisites:
- pip install diagrams
- Graphviz installed (choco install graphviz / brew install graphviz / apt install graphviz)

Generate PNG: python architecture.py
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.network import (
    FrontDoors,
    VirtualNetworks,
    Subnets,
    NetworkSecurityGroupsClassic,
    PrivateEndpoint,
    DNSZones
)
from diagrams.azure.compute import AppServices, FunctionApps
from diagrams.azure.database import SQLDatabases, CacheForRedis
from diagrams.azure.security import KeyVaults
from diagrams.azure.devops import ApplicationInsights
from diagrams.azure.analytics import LogAnalyticsWorkspaces
from diagrams.azure.integration import ServiceBus
from diagrams.azure.web import AppServicePlans
from diagrams.azure.general import Resourcegroups
from diagrams.onprem.client import Users

# Diagram configuration
graph_attr = {
    "fontsize": "28",
    "bgcolor": "white",
    "pad": "0.5",
    "splines": "spline",
    "nodesep": "0.8",
    "ranksep": "1.2"
}

node_attr = {
    "fontsize": "12"
}

edge_attr = {
    "fontsize": "10"
}

with Diagram(
    "Multi-Tier E-Commerce Platform\nPCI-DSS Compliant Architecture",
    show=False,
    direction="TB",
    filename="ecommerce_architecture",
    graph_attr=graph_attr,
    node_attr=node_attr,
    edge_attr=edge_attr,
    outformat="png"
):
    # External users
    users = Users("European\nCustomers")

    # Azure Front Door with WAF
    with Cluster("Edge Layer - Global"):
        frontdoor = FrontDoors(
            "Azure Front Door\nStandard + WAF\n(OWASP Rules)")

    # Static Web Apps (outside VNet - global edge)
    with Cluster("Static Web Apps - Global Edge"):
        spa = AppServices("React SPA\nStatic Web Apps\nStandard Tier")

    # Main Azure Region
    with Cluster("Azure Region: Sweden Central"):

        # Resource Group
        with Cluster("Resource Group: rg-ecommerce-prod"):

            # Monitoring cluster
            with Cluster("Monitoring"):
                app_insights = ApplicationInsights("Application\nInsights")
                log_analytics = LogAnalyticsWorkspaces(
                    "Log Analytics\n90-day retention")

            # Virtual Network
            with Cluster("VNet: vnet-prod-main-swc (10.0.0.0/16)"):

                # Web Tier Subnet
                with Cluster("snet-web-prod (10.0.1.0/24)"):
                    nsg_web = NetworkSecurityGroupsClassic(
                        "NSG-Web\nAllow 443 from\nFront Door only")
                    with Cluster("App Service Plan (P1v3 Zone Redundant)"):
                        app_service = AppServices(
                            ".NET 8 REST API\nApp Service\n(2+ instances)")

                # Data Tier Subnet
                with Cluster("snet-data-prod (10.0.2.0/24)"):
                    nsg_data = NetworkSecurityGroupsClassic(
                        "NSG-Data\nAllow from\nWeb subnet only")
                    with Cluster("Private Endpoints"):
                        pe_sql = PrivateEndpoint("PE-SQL")
                        pe_redis = PrivateEndpoint("PE-Redis")
                        pe_search = PrivateEndpoint("PE-Search")

                    sql_db = SQLDatabases(
                        "Azure SQL\nS3 (100 DTU)\nAzure AD-only auth")
                    redis = CacheForRedis("Azure Cache\nfor Redis C2\n(6GB)")
                    # Note: Cognitive Search doesn't have a specific icon, using SQL as proxy
                    search = SQLDatabases(
                        "Cognitive Search\nS1 Standard\n(<100ms queries)")

                # Integration Tier Subnet
                with Cluster("snet-integration-prod (10.0.3.0/24)"):
                    nsg_integration = NetworkSecurityGroupsClassic(
                        "NSG-Integration\nAllow from\nWeb/Data subnets")
                    with Cluster("Async Processing"):
                        pe_servicebus = PrivateEndpoint("PE-ServiceBus")
                        service_bus = ServiceBus(
                            "Service Bus\nPremium\n(Order Queue)")
                        functions = FunctionApps(
                            "Azure Functions\nEP1\n(Order Processing)")

            # Key Vault (accessible via managed identity)
            keyvault = KeyVaults("Key Vault\nStandard\n(Secrets)")

            # Private DNS Zones
            dns = DNSZones("Private DNS\nZones")

    # Data Flow Connections
    users >> Edge(label="HTTPS", color="darkgreen") >> frontdoor

    frontdoor >> Edge(label="CDN", color="blue") >> spa
    frontdoor >> Edge(label="API Traffic\n(WAF filtered)",
                      color="darkgreen") >> app_service

    # App Service connections
    app_service >> Edge(label="Managed Identity",
                        color="purple", style="dashed") >> keyvault
    app_service >> Edge(label="Product Data",
                        color="orange") >> pe_sql >> sql_db
    app_service >> Edge(label="Session Cache",
                        color="red") >> pe_redis >> redis
    app_service >> Edge(label="Search Queries\n(<100ms)",
                        color="teal") >> pe_search >> search
    app_service >> Edge(label="Order Messages",
                        color="brown") >> pe_servicebus >> service_bus

    # Functions processing
    service_bus >> Edge(label="Queue Trigger", color="brown") >> functions
    functions >> Edge(label="Order Data", color="orange") >> sql_db
    functions >> Edge(label="Secrets", color="purple",
                      style="dashed") >> keyvault

    # Monitoring connections (dashed lines for telemetry)
    app_service >> Edge(color="gray", style="dashed") >> app_insights
    functions >> Edge(color="gray", style="dashed") >> app_insights
    app_insights >> Edge(color="gray", style="dashed") >> log_analytics

    # DNS resolution
    pe_sql >> Edge(style="dotted", color="lightgray") >> dns
    pe_redis >> Edge(style="dotted", color="lightgray") >> dns
    pe_search >> Edge(style="dotted", color="lightgray") >> dns
    pe_servicebus >> Edge(style="dotted", color="lightgray") >> dns


if __name__ == "__main__":
    print("Generating architecture diagram...")
    print("Output: ecommerce_architecture.png")
