"""
Azure Architecture Diagram: Agent Testing & Validation Framework
Generated by Diagram agent
Date: 2026-01-22

Prerequisites:
- pip install diagrams
- Graphviz installed (choco install graphviz / brew install graphviz / apt install graphviz)

Generate PNG: python 03-des-diagram.py
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.compute import AppServices, ContainerInstances
from diagrams.azure.database import SQLDatabases
from diagrams.azure.storage import StorageAccounts
from diagrams.azure.security import KeyVaults
from diagrams.azure.integration import ServiceBus
from diagrams.azure.general import Resourcegroups
from diagrams.onprem.vcs import Github
from diagrams.onprem.ci import GithubActions
from diagrams.generic.storage import Storage
from diagrams.generic.compute import Rack

# Diagram configuration
graph_attr = {
    "fontsize": "20",
    "bgcolor": "white",
    "pad": "0.5",
    "splines": "spline",
    "nodesep": "0.8",
    "ranksep": "1.0"
}

node_attr = {
    "fontsize": "12"
}

edge_attr = {
    "fontsize": "10"
}

with Diagram(
    "Agent Testing & Validation Framework",
    show=False,
    direction="TB",
    filename="03-des-diagram",
    outformat="png",
    graph_attr=graph_attr,
    node_attr=node_attr,
    edge_attr=edge_attr
):
    # External: GitHub Repository and Actions
    with Cluster("GitHub"):
        repo = Github("azure-agentic-infraops\nRepository")
        
        with Cluster("GitHub Actions CI/CD"):
            functional = GithubActions("Functional\nTests")
            integration = GithubActions("Integration\nTests")
            quality = GithubActions("Quality\nTests")
            azure_tests = GithubActions("Azure\nTests")
    
    # Golden Files Storage (in Git)
    golden_files = Storage("Golden Files\n(Git Versioned)")
    
    # Azure Subscription
    with Cluster("Azure Subscription: noalz"):
        
        # Persistent Infrastructure
        with Cluster("Persistent Infrastructure"):
            automation = Rack("Azure Automation\n(Cleanup Runbooks)")
        
        # Ephemeral Test Resource Groups
        with Cluster("Ephemeral Test Resource Groups\nrg-agent-test-{scenario}-{timestamp}"):
            
            # Scenario 1: Static Web App (Smoke Test)
            with Cluster("Scenario 1: Static Web App"):
                swa = AppServices("Static Web Apps\n(Free Tier)")
            
            # Scenario 2: API with Database
            with Cluster("Scenario 2: API + Database"):
                app_service = AppServices("App Service\n(B1 Linux)")
                sql_db = SQLDatabases("Azure SQL\n(Basic 5 DTU)")
                kv1 = KeyVaults("Key Vault\n(Standard)")
            
            # Scenario 3: Microservices
            with Cluster("Scenario 3: Microservices"):
                container_apps = ContainerInstances("Container Apps\n(Consumption)")
                service_bus = ServiceBus("Service Bus\n(Basic)")
                storage = StorageAccounts("Storage Account\n(LRS)")
                kv2 = KeyVaults("Key Vault\n(Standard)")
    
    # Data Flow: Repository to Tests
    repo >> Edge(label="trigger") >> functional
    repo >> Edge(label="trigger") >> integration
    repo >> Edge(label="trigger") >> quality
    repo >> Edge(label="trigger") >> azure_tests
    
    # Golden file comparison
    functional >> Edge(label="compare", style="dashed") >> golden_files
    integration >> Edge(label="compare", style="dashed") >> golden_files
    
    # Azure Tests deploy resources
    azure_tests >> Edge(label="deploy/what-if", color="blue") >> swa
    azure_tests >> Edge(label="deploy/what-if", color="blue") >> app_service
    azure_tests >> Edge(label="deploy/what-if", color="blue") >> container_apps
    
    # Resource connections within Scenario 2
    app_service >> Edge(label="query") >> sql_db
    app_service >> Edge(label="secrets") >> kv1
    
    # Resource connections within Scenario 3
    container_apps >> Edge(label="messaging") >> service_bus
    container_apps >> Edge(label="blobs") >> storage
    container_apps >> Edge(label="secrets") >> kv2
    
    # Cleanup automation
    automation >> Edge(label="auto-delete\n(2h TTL)", color="red", style="dashed") >> swa
    automation >> Edge(label="auto-delete", color="red", style="dashed") >> app_service
    automation >> Edge(label="auto-delete", color="red", style="dashed") >> container_apps
